apiVersion: v1
kind: Service
metadata:
  name: namenode
  namespace: bigdata
spec:
  selector:
    app: namenode
  ports:
    - port: 8020
      targetPort: 8020
    - port: 9870
      targetPort: 9870
