apiVersion: v1
kind: Service
metadata:
  name: spark-master
  namespace: bigdata
spec:
  selector:
    app: spark-master
  ports:
    - port: 7077
      targetPort: 7077
    - port: 8080
      targetPort: 8080
