apiVersion: batch/v1
kind: Job
metadata:
  name: ohlcv-speed-job
  namespace: bigdata
spec:
  template:
    metadata:
      labels:
        app: ohlcv-speed
    spec:
      restartPolicy: OnFailure
      containers:
        - name: ohlcv-speed
          image: ohlcv_speed:latest
          envFrom:
            - configMapRef:
                name: bigdata-config
            - secretRef:
                name: airflow-secret
          command:
            - "spark-submit"
            - "--master"
            - "spark://spark-master:7077"
            - "--packages"
            - "org.elasticsearch:elasticsearch-spark-30_2.12:8.11.0,org.apache.spark:spark-sql-kafka-0-10_2.12:3.5.1"
            - "--conf"
            - "spark.jars.ivy=/tmp/.ivy2"
            - "/opt/spark/jobs/ohlcv_speed.py"
          resources:
            limits:
              memory: "500Mi"
              cpu: "0.5"
